stages:
  - clone
  - build
  - deploy

steps:
  Clone:
    type: git-clone
    stage: clone

  Package:
    title: Package component
    stage: build
    image: aws/codebuild/standard:4.0
    commands:
      - cd .microtica
      - npm install
      - npm run build
      - npm test
      - npm prune --production
      - cd functions/dbinit && npm run package
    artifacts:
      files:
        package_zip: ./.microtica/
        schema_json: ./.microtica/schema.json

  PushDockerImage:
    type: docker-push
    stage: build
    title: Build and Push Docker Image
    image_name: microtica/medusa-server
    registry: "{{CONTAINER_REGISTRY_ID}}"
    tag: "{{MIC_PIPELINE_EXECUTION_ID}}"
    dockerfile: ./.microtica/Dockerfile

  DeployComponent:
    type: deploy
    target: environment
    stage: deploy
    env_id: "{{ENV_ID}}"
    partial:
        create_missing_resources: true
        resource_version_overrides:
          {{AppName}}: "{{MIC_PIPELINE_EXECUTION_ID}}"
